# Generated by Django 4.0.3 on 2022-04-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.CharField(default='CUS001', max_length=6, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
                ('role', models.CharField(default='Customer', max_length=8)),
            ],
            options={
                'verbose_name': 'User_detail',
                'verbose_name_plural': 'User-details',
            },
        ),
    ]
