# Generated by Django 4.0.3 on 2022-04-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Name',
            field=models.EmailField(max_length=254),
        ),
    ]
