# Generated by Django 4.0.3 on 2022-04-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_userdetail_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name': 'UserDetail', 'verbose_name_plural': 'UserDetails'},
        ),
        migrations.AddField(
            model_name='userdetail',
            name='Email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Name',
            field=models.CharField(max_length=30),
        ),
    ]
