# Generated by Django 4.0.3 on 2022-04-06 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_userdetail_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DressesDetail',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Dress_Name', models.CharField(max_length=20, unique=True)),
                ('cost', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'DressesDetail',
                'verbose_name_plural': 'DressesDetails',
            },
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('Id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Order_cost', models.PositiveIntegerField()),
                ('Order_type', models.CharField(max_length=4)),
                ('Order_date', models.DateTimeField()),
                ('Cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_id', to='customer.userdetail')),
                ('Emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_id', to='customer.userdetail')),
            ],
            options={
                'verbose_name': 'OrderDetail',
                'verbose_name_plural': 'OrderDetails',
            },
        ),
    ]
