# Generated by Django 4.0.3 on 2022-04-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_userdetail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('Manager', 'Manager'), ('Admin', 'Admin')], default='Customer', max_length=8),
        ),
    ]
