# Generated by Django 4.0.3 on 2022-04-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_userdetail_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='id',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='Id',
            field=models.SmallAutoField(default='100', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dressesdetail',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
