# Generated by Django 4.0.3 on 2022-04-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_userdetail_id_userdetail_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
