# Generated by Django 4.0.3 on 2022-04-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_userdetail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressesdetail',
            name='Images',
            field=models.CharField(default='', max_length=15),
        ),
    ]
