# Generated by Django 4.0.3 on 2022-04-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_dressesdetail_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dressesdetail',
            name='Images',
            field=models.CharField(default='', max_length=25),
        ),
    ]
