# Generated by Django 4.0.3 on 2022-04-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_dressesdetail_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dressesdetail',
            name='Images',
        ),
    ]
