# Generated by Django 4.0.3 on 2022-04-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_remove_dressesdetail_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='Machine',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='Time_Slot',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Order_date',
            field=models.DateField(),
        ),
    ]
