# Generated by Django 4.0.3 on 2022-04-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_orderdetail_machine_orderdetail_time_slot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dressesdetail',
            old_name='cost',
            new_name='Cost',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='Contact',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
