# Generated by Django 4.0.3 on 2022-04-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_rename_cost_dressesdetail_cost_userdetail_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coupon', models.CharField(max_length=6)),
                ('Discount', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
    ]
