# Generated by Django 4.0.3 on 2022-04-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='Coupon',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
