# Generated by Django 4.0.3 on 2022-04-26 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_alter_coupon_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='Pickup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
