# Generated by Django 4.0.3 on 2022-04-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_orderdetail_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='Coupon',
            field=models.CharField(default='', max_length=6),
        ),
    ]
