# Generated by Django 4.0.3 on 2022-05-02 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_orderdetail_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='Order_type',
            field=models.CharField(choices=[('Dry', 'Dry'), ('Wash', 'Wash')], max_length=4),
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('FeedbackId', models.SmallAutoField(primary_key=True, serialize=False)),
                ('Feedback', models.TextField(max_length=150)),
                ('Response', models.TextField(max_length=150)),
                ('Cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cust_id', to='customer.userdetail')),
            ],
            options={
                'verbose_name': 'FeedBack',
                'verbose_name_plural': 'FeedBacks',
            },
        ),
    ]
