# Generated by Django 4.0.3 on 2022-04-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydetail',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
