# Generated by Django 4.0.3 on 2022-04-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_machines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machines',
        ),
    ]
