# Generated by Django 4.0.3 on 2022-04-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_delete_machines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('Machine_name', models.CharField(max_length=10, unique=True)),
                ('Type', models.CharField(choices=[('dryer', 'Dryer'), ('washer', 'Washer')], max_length=6)),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
            },
        ),
    ]
