# Generated by Django 4.0.3 on 2022-04-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_machines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('Supply_Name', models.CharField(max_length=20, unique=True)),
                ('Quantity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
    ]
