# Generated by Django 4.0.3 on 2022-04-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
