# Generated by Django 4.0.3 on 2022-04-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_delete_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='Status',
            field=models.CharField(choices=[('working', 'Working'), ('damaged', 'Damaged')], default='working', max_length=7),
        ),
    ]
